channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=23.2.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.0
  - numpy==1.26.4
  - pandas==2.2.3
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
